server:
  port: 9099
  
spring:
  profiles:
    active:
    - prod
    
  datasource:
#    url: jdbc:mysql://localhost:3306/sybyl_demo_bank_api_db
#    username: root
#    password: root
    name: sybyl_demo_bank_api_db
    
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  
